### ISSUE TITLE
Nelson Config file error

### ISSUE THREAD

**Issue by praveenballa** [verydanny/iotaGoogleCloudInstance#1]
Hi, 

I followed all the instructions but I am repeatedly get this error. Please help.

```
praveen@iota-full-iotanode-praveenballa:~$ sudo service iota start
praveen@iota-full-iotanode-praveenballa:~$ sudo nelson --config /home/nelson/config.ini
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/home/nelson/config.ini'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/usr/lib/node_modules/nelson.cli/dist/nelson.js:36:36)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
praveen@iota-full-iotanode-praveenballa:~$ 
```

**Comment by verydanny** [comment]
@praveenballa 
`sudo service iota start` handles `sudo nelson --config /home/nelson/config.ini` for you, no need for you to type it in again. Also please do this:

1. Navigate to home/nelson: `cd /home/nelson/`.
2. Type `ls -a`, what do you see?

**Comment by praveenballa** [comment]
@verydanny I see

`.  ..  .bash_logout  .bashrc  .profile  config.ini`

**Comment by praveenballa** [comment]
@verydanny 

1. Thank you for your quick response. Here is the message I keep getting. Is there a time I should wait before getting a response?

<img width="741" alt="praveen_iota-full-iotanode-praveenballa___" src="https://user-images.githubusercontent.com/23219508/34421299-859c8a30-ec34-11e7-8d26-80479a8a471e.png">

2. I followed your instructions for the server settings and I am getting a "increase performance" notice. Should I update?

<img width="515" alt="compute_engine_-_iotapraveenballa2" src="https://user-images.githubusercontent.com/23219508/34421350-d332a4d2-ec34-11e7-9903-062307123594.png">

**Comment by verydanny** [comment]
It means your cores are getting taxed, lots of CPU usage. I'd just be patient.

**Comment by praveenballa** [comment]
OK. Thank you. I will wait and will update you if anything changes :)
